language: java
jobs:
  include:
    - stage: Package 
      before_script: cd cake-api
      script : mvn clean install

    - stage: Run Backend Apps Integration Tests 
      before_script: cd cake-api 
      script :
       - mvn clean install
       - docker-compose up --build -d
      after_script: cd cake-manager-integration-test 
      script: mvn clean test  
