language: java
jobs:
  include:
    - stage: test
      before_script: cd cake-manager
      script : mvn clean install
    - stage: dockerize
      before_script: cd .. 
script: docker-compose up --build -d